const config = {
    repository: {
      name: 'svg-export-plugin',
      iconExtractPath: 'libs/common/icon',
      baseBranchName: 'master',
      owner: 'ahnkwang7379',
    },
    commit: {
      message: '[feat] update icons',
      author: {
        name: 'ahnkwang7379',
        email: 'ahnkwang7379@gmail.com',
      },
    },
    pr: {
      title: '[feat] update icons',
      body: 'Please check the changed part!\n---\nThis Pull Request was generated by svg-sprite-export-plugin.',
      labels: ['feat:icon'],
    },
  };
  
  export default config;